version: "2.0"
services:
  katacomb:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: katacomb
    image: sdp-docker-registry.kat.ac.za:5000/katsdpcontim
    network_mode: host
    restart: "no"
    hostname: katacomb
    volumes:
      - /var/kat/archive2:/var/kat/archive2:ro

  katacomb-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev

    container_name: katacomb-dev
    image: sdp-docker-registry.kat.ac.za:5000/katsdpcontim-dev
    network_mode: host
    restart: "no"
    hostname: katacomb-dev
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - /var/kat/archive2:/var/kat/archive2:ro
