FROM obit:trusty-dev
MAINTAINER simon.perkins@gmail.com

ENV PACKAGES \
    cvs \
    wget

RUN apt-get -y update && \
    apt-get install -y $PACKAGES

WORKDIR /usr/local/AIPS

RUN wget ftp://ftp.aoc.nrao.edu/pub/software/aips/31DEC16/install.pl

# Remove root user check:
RUN sed -i -e '455,461d' install.pl

## INSTALL AIPS - the here string just cycles through the aips install menu with (mostly) defaults.
RUN ["/bin/bash","-c","aipscmd=$'\nroot\n\nSKACOMM\nY\n\n\n/usr/local/AIPS/DATA/LOCALHOST_1\n\n\n\n\n\n\n\n\n\n\n' && perl install.pl -n <<< \"$aipscmd\""]

# Replace /etc/services with those required by aips
COPY services /etc/services

# Add the AIPS running script
ADD aipsrunner.sh /aipsrunner.sh

ENV OBIT_BASE_PATH /usr/local/Obit

# Add the Obit source code
ADD Obit/trunk $OBIT_BASE_PATH

# Add OBIT patch
ADD obit.patch $OBIT_BASE_PATH/obit.patch

# Apply OBIT patch
RUN cd $OBIT_BASE_PATH && \
    patch -p1 -N  < obit.patch 2>/dev/null

# Compile OBIT
RUN cd $OBIT_BASE_PATH/ObitSystem/Obit && \
    ./configure --prefix=/usr --without-plplot --without-wvr && \
    make clean && \
    make -j 8

# Add OBIT setup script
ADD setup_obit.sh /setup_obit.sh

RUN /setup_obit.sh

# Run aipsrunner.sh and then go to interactive shell
CMD ["/bin/bash", "--rcfile", "/aipsrunner.sh", "-i"]