version: "2.0"
services:
  xenial-obit:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: xenial-obit
    image: obit/xenial:latest
    network_mode: host
    restart: "no"
    hostname: xenial-obit
    volumes:
      - /var/kat/archive2:/var/kat/archive2:ro

  xenial-obit-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev

    container_name: xenial-obit-dev
    image: obit/xenial:dev
    network_mode: host
    restart: "no"
    hostname: xenial-obit-dev
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - /var/kat/archive2:/var/kat/archive2:ro
