version: "2.0"
services:
  trusty-obit-dev:
    build:
      context: ..
      dockerfile: katsdpcontim/Dockerfile.trusty.dev
      args:
        HTTP_PROXY: "http://localhost:3128"

    container_name: trusty-obit-dev
    image: trusty/obit:dev
    network_mode: bridge
    restart: "no"
    hostname: trusty-obit
    environment:
      - DISPLAY
    volumes:
      - ./work:/work:rw

  xenial-obit-dev:
    build:
      context: ..
      dockerfile: katsdpcontim/Dockerfile.xenial.dev
      args:
        HTTP_PROXY: "http://localhost:3128"

    container_name: xenial-obit-dev
    image: xenial/obit:dev
    network_mode: bridge
    restart: "no"
    hostname: xenial-obit
    environment:
      - DISPLAY
    volumes:
      - ./work:/work:rw
