version: "2.0"
services:
  xenial-obit-dev:
    build:
      context: ..
      dockerfile: katsdpcontim/Dockerfile.xenial.dev

    container_name: xenial-obit-dev
    image: obit/xenial:dev
    network_mode: host
    restart: "no"
    hostname: xenial-obit
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    # tmpfs:
    #   - /usr/local/AIPS/DATA/LOCALHOST_2:size=4g
    volumes:
      - $HOME/.local/katacomb/aipsmounts/AIPS:/usr/local/AIPS/DATA/LOCALHOST_1:rw
      - $HOME/.local/katacomb/aipsmounts/FITS:/usr/local/AIPS/FITS:rw
